import { existsSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import manifest from '../assets/heroes/heroes.json'

/**
 * The hero variants are generated by `npm run optimize:heroes` and committed, so
 * nothing at build time would notice if the manifest and the committed files
 * drifted apart — a missing width simply disappears from the srcset, and a
 * missing fallback renders a broken image on four routes.
 *
 * These assertions are about the contract between `heroes.json`, the files on
 * disk and the glob in `HeroImage.tsx`. They deliberately do not decode the
 * images; the generator checks the master dimensions when it writes them.
 */
const HERO_DIR = join(__dirname, '../assets/heroes')
const heroNames = Object.keys(manifest.heroes) as Array<keyof typeof manifest.heroes>

describe('hero manifest', () => {
  it('declares at least one width and a fallback among them', () => {
    expect(manifest.widths.length).toBeGreaterThan(0)
    expect(manifest.widths).toContain(manifest.fallbackWidth)
  })

  it('lists widths in ascending order, so the srcset reads as a ladder', () => {
    expect([...manifest.widths].sort((a, b) => a - b)).toEqual(manifest.widths)
  })

  it('names every hero used by a route', () => {
    expect(heroNames).toEqual([
      'bangladesh-flood-2020',
      'cyclone-freddy-madagascar-2023',
      'zambia-drought-2024',
    ])
  })

  it('records a plausible master size for each hero', () => {
    heroNames.forEach((name) => {
      const hero = manifest.heroes[name]
      expect(hero.width).toBeGreaterThan(manifest.fallbackWidth)
      expect(hero.height).toBeGreaterThan(0)
      expect(hero.source).toMatch(/\.jpg$/)
    })
  })
})

describe('committed hero variants', () => {
  it('has an AVIF and a WebP at every declared width', () => {
    heroNames.forEach((name) => {
      manifest.widths.forEach((width) => {
        ['avif', 'webp'].forEach((extension) => {
          const file = join(HERO_DIR, `${name}-${width}.${extension}`)
          expect(existsSync(file), `${name}-${width}.${extension} is missing`).toBe(true)
          expect(statSync(file).size).toBeGreaterThan(0)
        })
      })
    })
  })

  it('has the JPEG fallback every <img> src points at', () => {
    heroNames.forEach((name) => {
      const file = join(HERO_DIR, `${name}-${manifest.fallbackWidth}.jpg`)
      expect(existsSync(file), `${name} fallback is missing`).toBe(true)
    })
  })

  it('keeps every variant smaller than a quarter of a megabyte at 1024', () => {
    // The point of the exercise: a hero at a phone-sized width must not be a
    // multi-megabyte download again.
    heroNames.forEach((name) => {
      expect(statSync(join(HERO_DIR, `${name}-1024.avif`)).size).toBeLessThan(262_144)
    })
  })

  it('ships no master JPEG inside the bundle directory', () => {
    // The 4,000-5,700 px originals live in assets-source and must stay there:
    // anything in src/assets is a candidate for the deployment payload.
    heroNames.forEach((name) => {
      expect(existsSync(join(HERO_DIR, `${name}.jpg`))).toBe(false)
    })
  })
})
