import { existsSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import manifest from '../assets/heroes/heroes.json'

/**
 * The hero variants are generated by `npm run optimize:heroes` and committed, so
 * nothing at build time would notice if the manifest and the committed files
 * drifted apart — a missing width simply disappears from the srcset, and a
 * missing fallback renders a broken image on four routes.
 *
 * These assertions are about the contract between `heroes.json`, the files on
 * disk and the glob in `HeroImage.tsx`. They deliberately do not decode the
 * images; the generator checks the master dimensions when it writes them.
 */
const HERO_DIR = join(__dirname, '../assets/heroes')
const heroNames = Object.keys(manifest.heroes) as Array<keyof typeof manifest.heroes>

/** The widths the generator will write for a hero: never wider than its master. */
function widthsFor(name: keyof typeof manifest.heroes) {
  return manifest.widths.filter((width) => width <= manifest.heroes[name].width)
}

describe('hero manifest', () => {
  it('declares at least one width and a fallback among them', () => {
    expect(manifest.widths.length).toBeGreaterThan(0)
    expect(manifest.widths).toContain(manifest.fallbackWidth)
  })

  it('lists widths in ascending order, so the srcset reads as a ladder', () => {
    expect([...manifest.widths].sort((a, b) => a - b)).toEqual(manifest.widths)
  })

  it('names every hero used by a route', () => {
    expect(heroNames).toEqual([
      'cyclone-freddy-madagascar-2023',
      'zambia-drought-2024',
      'drc-ndjili-market-gardens-2025',
      'drc-ndjili-field-team-2025',
      'syria-earthquake-impact-2023',
      'afghanistan-f2f-smartphone-interview-2024',
      'afghanistan-household-visit-round-10-2025',
      'drc-field-mission-team-2025',
      'bangladesh-haor-flood-2024',
      'guatemala-maize-field-interview-2022',
      'drc-phone-interview-round-8-2024',
      'drc-ndjili-rice-threshing-2025',
      'drc-ndjili-threshing-team-2025',
      'drc-ndjili-rice-inspection-2025',
      'car-ouadda-interview-2024',
      'car-bria-interview-2024',
      'drc-diem-officers-2023',
      'colombia-quipama-doorstep-2023',
      'syria-earthquake-assessment-2023',
      'drc-ndjili-rice-harvest-2025',
    ])
  })

  it('records a plausible master size for each hero', () => {
    // Not every master clears `fallbackWidth`: the FAO photographs are served at
    // 1,024 px and the generator refuses to upscale past that, so the floor here
    // is the narrowest width the ladder declares.
    heroNames.forEach((name) => {
      const hero = manifest.heroes[name]
      expect(hero.width).toBeGreaterThanOrEqual(Math.min(...manifest.widths))
      expect(hero.height).toBeGreaterThan(0)
      expect(hero.source).toMatch(/\.jpg$/)
    })
  })
})

describe('committed hero variants', () => {
  it('has an AVIF and a WebP at every width its master can supply', () => {
    heroNames.forEach((name) => {
      widthsFor(name).forEach((width) => {
        ['avif', 'webp'].forEach((extension) => {
          const file = join(HERO_DIR, `${name}-${width}.${extension}`)
          expect(existsSync(file), `${name}-${width}.${extension} is missing`).toBe(true)
          expect(statSync(file).size).toBeGreaterThan(0)
        })
      })
    })
  })

  it('writes nothing above a master width, so no srcset candidate is an upscale', () => {
    // A file named `-2048` generated from a 1,024 px master would tell the
    // browser it is choosing 2,048 px of detail that does not exist.
    heroNames.forEach((name) => {
      manifest.widths
        .filter((width) => width > manifest.heroes[name].width)
        .forEach((width) => {
          ['avif', 'webp', 'jpg'].forEach((extension) => {
            const file = join(HERO_DIR, `${name}-${width}.${extension}`)
            expect(existsSync(file), `${name}-${width}.${extension} is an upscale`).toBe(false)
          })
        })
    })
  })

  it('has the JPEG fallback every <img> src points at', () => {
    // Mirrors `fallback()` in HeroImage.tsx: the widest JPEG at or below
    // `fallbackWidth` that the master was large enough to produce.
    heroNames.forEach((name) => {
      const width = Math.max(...widthsFor(name).filter((candidate) => candidate <= manifest.fallbackWidth))
      const file = join(HERO_DIR, `${name}-${width}.jpg`)
      expect(existsSync(file), `${name} fallback is missing`).toBe(true)
    })
  })

  it('keeps every variant smaller than a quarter of a megabyte at 1024', () => {
    // The point of the exercise: a hero at a phone-sized width must not be a
    // multi-megabyte download again. A master narrower than 1024 has no such
    // variant, so its widest one stands in.
    heroNames.forEach((name) => {
      const width = Math.max(...widthsFor(name).filter((w) => w <= 1024), manifest.widths[0])
      expect(statSync(join(HERO_DIR, `${name}-${width}.avif`)).size).toBeLessThan(262_144)
    })
  })

  it('ships no master JPEG inside the bundle directory', () => {
    // The 4,000-5,700 px originals live in assets-source and must stay there:
    // anything in src/assets is a candidate for the deployment payload.
    heroNames.forEach((name) => {
      expect(existsSync(join(HERO_DIR, `${name}.jpg`))).toBe(false)
    })
  })
})
