import fs from 'node:fs'

/**
 * Regenerates src/icons.css from the bootstrap-icons package.
 *
 * Run after adding a bi-* class to a component, and add its name below.
 * Keep this list in sync with: grep -rhoE "bi bi-[a-z0-9-]+" src/
 */
const NAMES = [
  'box-arrow-up-right',
  'chevron-left',
  'chevron-right',
  'dash-lg',
  'download',
  'file-earmark-pdf',
  'plus-lg',
]

const encode = (svg) => svg
  .replace(/</g, '%3C')
  .replace(/>/g, '%3E')
  .replace(/#/g, '%23')

const glyph = (name) => {
  const raw = fs.readFileSync(`node_modules/bootstrap-icons/icons/${name}.svg`, 'utf8')
  const inner = raw
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/\s+/g, ' ')
    // The shipped paths quote their attributes with ", which would close the
    // CSS url("...") string early and leave mask-image invalid - an icon drawn
    // as a solid square. Single quotes are equally valid in SVG.
    .replace(/"/g, "'")
    .trim()
  return encode(`<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'>${inner}</svg>`)
}

const header = `/*
 * The seven Bootstrap Icons this application actually uses.
 *
 * The vendored FAO theme pulled the whole icon font from cdn.jsdelivr.net inside
 * a render-blocking @import: a serial round trip before first paint, a 134 kB
 * webfont for seven glyphs, a third-party origin that can be blocked or slow in
 * the contexts DIEM serves, and a commercial CDN learning the IP of every
 * visitor to an FAO site. This file is 5 kB and costs no request at all.
 *
 * These are masks rather than inline <svg>, for two reasons. The glyphs are
 * fill-based, while the global rule at styles.css:55 sets fill:none and
 * stroke:currentColor on every svg that is not a map - inlining them would draw
 * nothing. And a mask keeps the existing <i class="bi bi-x"> markup and
 * currentColor behaviour, so no component changed.
 *
 * The url is set through mask-image longhand rather than the mask shorthand.
 * A var() inside a shorthand is validated only at computed-value time, and when
 * it fails there the whole shorthand resets to its initial value - which is
 * mask-image: none, and an icon that renders as a solid square.
 *
 * Generated by scripts/generate-icons.mjs. Do not edit by hand.
 */
.bi {
  display: inline-block;
  width: 1em;
  height: 1em;
  vertical-align: -.125em;
  background-color: currentColor;
  -webkit-mask-repeat: no-repeat;
  mask-repeat: no-repeat;
  -webkit-mask-position: center;
  mask-position: center;
  -webkit-mask-size: contain;
  mask-size: contain;
}
`

const rules = NAMES.map((name) => {
  const url = `url("data:image/svg+xml,${glyph(name)}")`
  return `.bi-${name} { -webkit-mask-image: ${url}; mask-image: ${url}; }`
})

fs.writeFileSync('src/icons.css', `${header}\n${rules.join('\n')}\n`)
console.log(`wrote src/icons.css: ${NAMES.length} glyphs, ${fs.statSync('src/icons.css').size} bytes`)
